### ISSUE TITLE
issue with getting the code to work

### ISSUE THREAD

**Issue by ghost** [choogiesaur/hgss-shiny-modifier#1]
can you leave an example so i know EXACTLY what to change because it's confusing and for some reason it just closes without doing anything ;-;

**Comment by choogiesaur** [comment]
Hi, please check the updated version of the repo. 

It now takes your filename to be modified via command line argument.

You still set your region and shiny rate in the script on these lines:
```
shiny_offset = 0x70080
...
new_shiny_rate = 0xFF
```

You can change either the 0x70080 to the other regions listed, or 0xFF to a shiny rate of your choice.

**Comment by choogiesaur** [comment]
Thanks for your interest and please report any further bugs!

**Comment by ghost** [comment]
Hi, Im sorry if im just really incompetent for step 5 & 6 but do I just run the code in visual studio and how will if I've completed the steps right?
Thanks

**Comment by MetaSamsara** [comment]
> Hi, Im sorry if im just really incompetent for step 5 & 6 but do I just run the code in visual studio and how will if I've completed the steps right? Thanks

- You shift right click in the script folder after putting the rom in it and select "Open command prompt here".
- In the command prompt you type the line `python shiny_rate_editor.py yourromname.nds 0x70080 0xFF` (replace the `0x70080` with your region's code if you don't use US rom).
- Note that the line in the readme is outdated, the script is now called `shiny_rate_editor.py` not `shiny_editor.py`. 
- After you press enter, the script should generate a new patched rom file called `shiny_rate_patched.nds`. Play this rom however you would play any rom.
